module.exports = {
    arrowParens: 'always',
    bracketSpacing: true,
    endOfLine: 'lf',
    htmlWhitespaceSensitivity: 'strict',
    jsxBracketSameLine: false,
    jsxSingleQuote: false,
    printWidth: 85,
    proseWrap: 'never',
    quoteProps: 'as-needed',
    semi: true,
    singleQuote: true,
    tabWidth: 4,
    trailingComma: 'es5',
    useTabs: true,
}
