// This file is automatically generated from your CSS. Any edits will be overwritten.
declare namespace StyleCssNamespace {
	export interface IStyleCss {
		fadein: string;
		lightbox: string;
		lightboxClose: string;
		lightboxContainer: string;
		overlay: string;
	}
}

declare const StyleCssModule: StyleCssNamespace.IStyleCss;

export = StyleCssModule;
