// This file is automatically generated from your CSS. Any edits will be overwritten.
declare namespace StyleCssNamespace {
	export interface IStyleCss {
		container: string;
		fileIcon: string;
		fileIconHidden: string;
		fileIconShow: string;
		input: string;
	}
}

declare const StyleCssModule: StyleCssNamespace.IStyleCss;

export = StyleCssModule;
