// This file is automatically generated from your CSS. Any edits will be overwritten.
declare namespace StyleCssNamespace {
	export interface IStyleCss {
		fromBottom: string;
		message: string;
		sendByUser: string;
	}
}

declare const StyleCssModule: StyleCssNamespace.IStyleCss;

export = StyleCssModule;
